# Generated by Django 3.1.7 on 2022-05-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20220518_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='picture',
            field=models.ImageField(default=1, upload_to='portfolio_images/'),
            preserve_default=False,
        ),
    ]
