# Generated by Django 3.1.7 on 2022-05-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_about_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio',
            field=models.CharField(max_length=255),
        ),
    ]
