# Generated by Django 3.1.7 on 2022-05-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20220518_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio',
            field=models.FileField(null=True, upload_to='videos_uploaded'),
        ),
    ]
