# Generated by Django 3.1.7 on 2022-05-18 19:24

from django.db import migrations, models
import website.validator


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20220518_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='picture',
            field=models.FileField(null=True, upload_to='portfolio_files/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio',
            field=models.FileField(null=True, upload_to='portfolio_files/', validators=[website.validator.validate_file_extension]),
        ),
    ]
