# Generated by Django 3.1.7 on 2022-05-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20220518_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
