# Generated by Django 3.1.7 on 2022-05-29 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200427_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrytoNew',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('guid', models.CharField(max_length=256)),
                ('imageurl', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=2000)),
                ('url', models.TextField(max_length=2000)),
                ('published_on', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cryptos', to='blog.category')),
            ],
            options={
                'ordering': ['-published_on'],
            },
        ),
    ]
