# Generated by Django 3.1.7 on 2021-10-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrytoNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=256)),
                ('imageurl', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=2000)),
                ('url', models.TextField(max_length=2000)),
                ('published_on', models.DateTimeField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
