# Generated by Django 3.1.7 on 2021-10-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_crytonews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrytoNews',
            new_name='CrytoNew',
        ),
    ]
