# Generated by Django 3.1.7 on 2021-10-10 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20211010_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crytonew',
            options={'ordering': ['-published_on']},
        ),
    ]
